version: '3'

services:
  postgres:
    container_name: nestjs-db-container
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /home/testuser1/docker/postgres:/var/lib/postgresql/data
      - /home/testuser1/docker/test1:/tmp/test
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
    networks:
      - nest-network

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-container
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - nest-network
    volumes:
      - ./.env:/usr/src/app/.env
networks:
  nest-network:
    driver: bridge
